name: Dependency Management

on:
  schedule:
    # Check for dependency updates weekly
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Check for outdated packages
      run: |
        pip list --outdated --format=json > outdated.json
        
    - name: Update requirements
      run: |
        pip-compile --upgrade requirements.in
        
    - name: Check security vulnerabilities
      run: |
        pip install safety
        safety check --json --output vulnerability-report.json

    - name: Create Pull Request for updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Automated dependency updates"
        body: |
          Automated dependency update created by GitHub Actions.
          
          **Changes:**
          - Updated requirements.txt with latest compatible versions
          - Security vulnerability check included
          
          Please review the changes before merging.
        branch: dependency-updates
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety pip-audit

    - name: Run safety check
      run: |
        safety check --json --output safety-report.json

    - name: Run pip-audit
      run: |
        pip-audit --format=json --output=audit-report.json

    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-audit-reports
        path: |
          safety-report.json
          audit-report.json
